### YamlMime:ManagedReference
items:
- uid: FastEndpoints.Swagger
  commentId: N:FastEndpoints.Swagger
  id: FastEndpoints.Swagger
  children:
  - FastEndpoints.Swagger.Extensions
  langs:
  - csharp
  - vb
  name: FastEndpoints.Swagger
  nameWithType: FastEndpoints.Swagger
  fullName: FastEndpoints.Swagger
  type: Namespace
  assemblies:
  - FastEndpoints.Swagger
references:
- uid: FastEndpoints.Swagger.Extensions
  commentId: T:FastEndpoints.Swagger.Extensions
  name: Extensions
  nameWithType: Extensions
  fullName: FastEndpoints.Swagger.Extensions
